apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: News Postgres
    uid: news-postgres
    type: postgres
    access: proxy
    url: news-database:5432
    database: ${DATA_POSTGRES_DB_NAME}
    user: ${DATA_POSTGRES_USER}
    secureJsonData:
      password: ${DATA_POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: true
